const axios = require('axios');
const PDFDocument = require('pdfkit');
const FormData = require('form-data');
const { downloadContentFromMessage } = require('@whiskeysockets/baileys');

// ─── Helpers ──────────────────────────────────────────────────────────────────
async function downloadBuffer(msgNode, type) {
  const stream = await downloadContentFromMessage(msgNode[type], type.replace('Message', ''));
  let buf = Buffer.from([]);
  for await (const chunk of stream) buf = Buffer.concat([buf, chunk]);
  return buf;
}

function getQuoted(mek) {
  if (mek.quoted?.message) return { message: mek.quoted.message, type: mek.quoted.type };
  let q = mek.message?.extendedTextMessage?.contextInfo?.quotedMessage;
  if (!q) return null;
  while (q?.ephemeralMessage || q?.viewOnceMessage || q?.viewOnceMessageV2 || q?.viewOnceMessageV2Extension) {
    q = q.ephemeralMessage?.message || q.viewOnceMessage?.message ||
        q.viewOnceMessageV2?.message || q.viewOnceMessageV2Extension?.message;
  }
  if (!q) return null;
  return { message: q, type: Object.keys(q)[0] };
}

// ─── Commands ─────────────────────────────────────────────────────────────────

module.exports = {

  // 🔍 OCR — extract text from a replied image
  ocr: async ({ sock, chatJid, mek }) => {
    const q = getQuoted(mek);
    if (!q || q.type !== 'imageMessage')
      return sock.sendMessage(chatJid, { text: '❌ Reply to an *image* with `.ocr` to extract its text.' }, { quoted: mek });

    await sock.sendMessage(chatJid, { text: '🔍 Scanning image for text...' }, { quoted: mek });

    try {
      const buf = await downloadBuffer(q.message, 'imageMessage');
      const form = new FormData();
      form.append('file', buf, { filename: 'scan.jpg', contentType: 'image/jpeg' });
      form.append('OCREngine', '2');
      form.append('isOverlayRequired', 'false');

      const res = await axios.post('https://api.ocr.space/parse/image', form, {
        headers: { ...form.getHeaders(), apikey: process.env.OCR_API_KEY || 'helloworld' },
        timeout: 30000
      });

      const text = res.data?.ParsedResults?.[0]?.ParsedText?.trim();
      if (!text) throw new Error('No readable text found in this image.');

      await sock.sendMessage(chatJid, {
        text: `📝 *[OCR EXTRACTED TEXT]*\n\n${text}`
      }, { quoted: mek });
    } catch (e) {
      await sock.sendMessage(chatJid, { text: `❌ OCR failed: ${e.message}` }, { quoted: mek });
    }
  },

  // 📄 PDF — compile replied text or image into a PDF document
  pdf: async ({ sock, chatJid, mek, text }) => {
    const q = getQuoted(mek);

    // Collect the content to embed
    let rawText = text;
    if (!rawText && q?.message?.conversation)            rawText = q.message.conversation;
    if (!rawText && q?.message?.extendedTextMessage?.text) rawText = q.message.extendedTextMessage.text;

    const hasImage = q?.type === 'imageMessage';

    if (!rawText && !hasImage)
      return sock.sendMessage(chatJid, {
        text: '❌ Usage:\n• `.pdf Your text here`\n• Reply to a *text message* with `.pdf`\n• Reply to an *image* with `.pdf`'
      }, { quoted: mek });

    await sock.sendMessage(chatJid, { text: '⏳ Generating PDF document...' }, { quoted: mek });

    try {
      const doc = new PDFDocument({ margin: 55 });
      const chunks = [];
      doc.on('data', c => chunks.push(c));

      doc.on('end', async () => {
        const pdfBuf = Buffer.concat(chunks);
        await sock.sendMessage(chatJid, {
          document: pdfBuf,
          mimetype: 'application/pdf',
          fileName: `Empire_MD_${Date.now().toString().slice(-6)}.pdf`,
          caption: '📄 *Your PDF is ready!* — Generated by Empire-MD'
        }, { quoted: mek });
      });

      // ── Header ──
      doc.fillColor('#1A365D').fontSize(22)
         .text('EMPIRE-MD · DOCUMENT', { align: 'center' });
      doc.moveDown(0.5);
      doc.strokeColor('#AAAAAA').lineWidth(1)
         .moveTo(55, doc.y).lineTo(540, doc.y).stroke();
      doc.moveDown(1.5);

      // ── Body ──
      if (hasImage) {
        const imgBuf = await downloadBuffer(q.message, 'imageMessage');
        doc.fillColor('#333333').fontSize(11)
           .text('Attached Image:', { underline: true });
        doc.moveDown(0.5);
        doc.image(imgBuf, { fit: [480, 380], align: 'center' });
      } else {
        doc.fillColor('#222222').fontSize(12)
           .text(rawText, { lineGap: 5, align: 'left' });
      }

      // ── Footer ──
      doc.moveDown(3);
      doc.fontSize(9).fillColor('#888888')
         .text(`Generated ${new Date().toLocaleString()} · Powered by Empire-MD`, { align: 'center' });

      doc.end();
    } catch (e) {
      await sock.sendMessage(chatJid, { text: `❌ PDF generation failed: ${e.message}` }, { quoted: mek });
    }
  }
};
